name: Node.js CI

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Change this to the Node.js version you want to use

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm start

    - name: Build
      run: npm build:prod 
       
    - name: EsLint ts/tsx
      run: npm lint:ts  

    - name: Eslint scss
      run: npm lint:scss  
 

